server:
  port: 8080
  servlet:    context-path: /basi-rest-app
spring:
 datasource:    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin 
    password: admin h2:     console:      enabled: true
